name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate HTML Documentation
      run: |
        export PATH="$PATH:/usr/local/bin/python3"
        mkdir -p docs
        for file in $(find . -name "*.py"); do
            module=$(basename "$file" .py)
            python3 -m pydoc -w "$module"
            mv "$module.html" docs/
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
